### ISSUE TITLE
Troubleshooting section not available in docs

### ISSUE THREAD

**Issue by ccc-dvansevenant** [daytonaio/docs#185]
While troubleshooting my server issues and running a debug log, I saw the link for the troubleshooting page appear:

![image](https://github.com/user-attachments/assets/36263688-e297-40d3-96c7-a5c5aab1afcb)

Following the link failed.

Working my way through other issues I stumbled across PR184 (https://github.com/daytonaio/docs/pull/184) which referenced the new Troubleshooting section from 3 days ago (as of this writing). Browsing the source shows the new section exists, however, following the Documentation link from the main Daytona Github page shows the Troubleshooting section does not exist:

![image](https://github.com/user-attachments/assets/504da746-b26f-4de5-a05b-42afbc9c8795)

![image](https://github.com/user-attachments/assets/c5352c84-9a8d-4b69-9274-b7b75351e789)

Just thought I'd note this.

-- Dion

**Comment by stefanicjuraj** [comment]
I believe this is due to the latest documentation changes (including the troubleshooting section) not being deployed publicly yet - once it is deployed, it should be visible. @Tpuljak 

If you run the documentation locally, the troubleshooting section is visible.

<img width="1218" alt="troubleshooting" src="https://github.com/user-attachments/assets/264b34fc-d744-4202-8720-136452e2f151">

**Comment by Tpuljak** [comment]
@ccc-dvansevenant thanks for letting us know 😄

We deployed the new version just now.

https://www.daytona.io/docs/misc/troubleshooting/

Sorry for the inconvenience.

Closing the issue.
