### ISSUE TITLE
Spacing Issues across Daytona.io

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/docs#43]
None of the spacings seem to be consist and very few are correct.

Please refer to Figma for correct spacing
<img width="541" alt="Screenshot 2024-05-31 at 16 18 18" src="https://github.com/daytonaio/docs/assets/11191224/9d8ccab2-6dad-43eb-ad53-820c79a3d4d6">
Also make sure to correct this on dotfiles, Documentation, Contact, Changelog, Definitions...
@mikimih

**Comment by Swearengen** [comment]
I think I fixed some issues with spacing inside markdown content.
The problem is that inside figma I couldn't find spacing numbers for the headings `h3`, `h4`, etc. Also the markdown uses `ul` and `ol` and I couldn't find spacing for that elements.
If the changes I did in the PR are not good enough we need to discuss above problems

**Comment by ivan-burazin** [comment]
Hey @Swearengen can you reuse spacing settings from https://fly.io/docs/? as i feel the spacing, especially `ul` and `ol` are still a bit large.

Thanks!
