### ISSUE TITLE
Update of installation page

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/docs#45]
I really like how Fly structured their CLI installation page: [Fly CLI Installation](https://fly.io/docs/hands-on/install-flyctl/).

The content bar clearly shows what a user is looking for, whether it’s Win/Mac/Linux, and is organized with user needs in mind. Additionally, package managers are listed under the OS they fit.

**Comment by osslate** [comment]
Because we also detail 3rd party package managers (Nix, Brew), and both of these support multiple OSes (macOS, Linux), this wouldn't work as well as it does on the Fly CLI Installation docs. Separating the docs by OS would mean duplicating a lot of the same instructions, which ideally we should avoid.

An alternative is to use the tabbed UI in #47 and use it to condense the page.

**Comment by ivan-burazin** [comment]
Disagree

The user is looking for a solution to their issue - Install Daytona on OS X, Y or Z.

The content may duplicate for you, but for the reader all their info is in one place.

**Comment by osslate** [comment]
Fair point. I'm thinking about the page becoming cluttered if we opt for this option with the current design implementation.

If we got the design for #47 implemented, we could have 3 tabs (macOS, Linux, Windows) on the installation page and do it that way. A lot of docs sites do that. It'd be much less overwhelming to the user and look a lot slicker in my opinion.

**Comment by osslate** [comment]
Settled on segregating the page into 3 sections based on OS (macOS, Linux, Windows).

**Comment by ivan-burazin** [comment]
@osslate were is the PR?
