### ISSUE TITLE
Brew

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/docs#46]
@idagelic can we get? brew install daytona so @osslate can update this everywhere?

**Comment by idagelic** [comment]
> @idagelic can we get? brew install daytona so @osslate can update this everywhere?
> 

@ivan-burazin please check Slack for this matter

**Comment by ivan-burazin** [comment]
`brew install daytona`

**Comment by ivan-burazin** [comment]
@idagelic  brew install daytona/tap/daytonaio ? or some other shortener?

**Comment by idagelic** [comment]
@ivan-burazin  Can't get it shorter than that right now - until we resolve the issue stopping us from getting `brew install daytona`

Splitting it to two commands is an option:
`brew tap daytonaio/daytona`
`brew install daytona`
It's not really better for a "quick start",  but a positive side is that you have then already "tapped" our repository and in the future `brew upgrade daytona` can be used to upgrade instead of needing to write `brew upgrade daytonaio/daytona/daytona`

**Comment by osslate** [comment]
@idagelic which is standard when it comes to brew? I can update the instructions in the installation guide if splitting in two is the "better" option.

Ideally since the docs are versioned, we should be instructing users to install the specific version of Daytona. Not sure if that's possible with brew; it's also a bit tricky with Nix.

**Comment by idagelic** [comment]
@osslate Afaic we can keep it simply `brew install daytonaio/daytona/daytona` if someone wants to use brew.
There is currently no versioning even though that is possible within brew - we can document that when/if we switch to the official homebrew tap.

**Comment by ivan-burazin** [comment]
What is the issues with TAP?

**Comment by idagelic** [comment]
I don't understand your question

**Comment by ivan-burazin** [comment]
why cant it be brew install daytonaio/tap/daytona instead of brew install daytonaio/daytona/daytona

**Comment by osslate** [comment]
As far as I understand, for illustration:

- `brew install <ORG>/<NAME>/<FORMULA>`:
  1. Homebrew clones the repository at `https://github.com/<ORG>/homebrew-<NAME>.git`
  2. Homebrew imports the file `<FORMULA>.rb` in the cloned repository
  3. Homebrew builds and installs according to `<FORMULA>.rb`

How it currently works:

- `brew install daytonaio/daytona/daytona`:
  1. Homebrew clones the repository at `https://github.com/daytonaio/homebrew-daytona.git`
  2. Homebrew imports the file `daytona.rb` in the cloned repository
  3. Homebrew builds and installs according to `daytona.rb`

And with the command you suggested:

- `brew install daytonaio/tap/daytona`:
  1. Homebrew clones the repository at `https://github.com/daytonaio/homebrew-tap.git`
  2. Homebrew imports the file `daytona.rb` in the cloned repository
  3. Homebrew builds and installs according to `daytona.rb`

Because of how Homebrew works, it seems common practice to name repositories and formulas this way. [See the list of "interesting taps" on Homebrew's docs](https://docs.brew.sh/Interesting-Taps-and-Forks). You can see repos are in this format, e.g. `homebrew-ffmpeg` => `brew install homebrew-ffmpeg/ffmpeg/ffmpeg`

**Comment by idagelic** [comment]
Thanks for the explanation @osslate 

@ivan-burazin Yes, if we change the repository name from "homebrew-daytona" to "homebrew-tap",  `brew install daytonaio/tap/daytona` would be possible. I didn't think of changing the repo name like that as I haven't seen anyone else do it - the part after "homebrew-" is usually the same as the app name in instances like ours where there is only one relevant package.

I just tried out this shortest option on my private acc: `brew install idagelic/d/daytona` and it works. Still, I don't know if I would go for this setup as it is not the standard

**Comment by ivan-burazin** [comment]
brew tap daytonaio/daytona
brew install daytona

Is fine but would like to shorten the brew install daytonaio/daytona/daytona - > brew install daytonaio/tap/daytona if there are no hard arguments against.

Lmk and will open a new issue on Daytona. thanks

**Comment by idagelic** [comment]
@ivan-burazin No problem, please open up an issue and add a "discussion" tag

**Comment by idagelic** [comment]
v0.18.0+ now live on `brew install daytonaio/tap/daytona`
Let me know if everything works correctly and I will close the issue.

Btw, you might have to run `brew uninstall daytonaio/daytona/daytona` first
