### ISSUE TITLE
Uninstall command does not work in Ubuntu

### ISSUE THREAD

**Issue by inovakdayt** [daytonaio/docs#90]
command for posix compatible shell:
```
daytona purge
sudo rm $(where daytona)
```
does not work in Ubuntu 20.04. Command `where` does not exist

**Comment by Anshgrover23** [comment]
in linux we use `whereis`  instead of `where`

**Comment by Divanshu-Grover** [comment]
@Tpuljak we should use `whereis` instead of `where` as in most of linux distros `whereis` works perfectly while `where` command is only useful for some specified distros which i have not seen yet . also i want to specify that `where` command works fine and is only useful there. Hence I , Divanshu Grover request you to please reply me on this topic .

**Comment by Tpuljak** [comment]
@Divanshu-Grover I understand your point.

The reason we chose to use `where` is that it returns only the path, while `whereis` returns `binaryName: PATH` so `sudo rm $(whereis daytona)` would not work in that scenario.

Nevertheless, I suggest that we remove `sudo $(where daytona)` from the docs instructions altogether since, with https://github.com/daytonaio/daytona/pull/897, the purge process now displays the exact path of the binary so `sudo $(where daytona)` became obsolete.

**Comment by Divanshu-Grover** [comment]
@Tpuljak I think you could have used `which` instead of `where`  and  below is the proof that which gives output same as where i.e. It returns only the path
![image](https://github.com/user-attachments/assets/bc6ff77d-5a57-4821-ae81-50f599483fcc)

**Comment by Divanshu-Grover** [comment]
Hi @Tpuljak ,

I've submitted a PR that addresses the issue with the uninstall command in both the macOS and Unix[linux] documentation. The commands have been updated to ensure proper uninstallation of daytona. Please review and let me know if any further adjustments are needed.
